In [1]:
import pandas as pd

In [40]:
df = pd.read_excel('default_of_credit_card_clients.xls')
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

In [3]:
import numpy as np

In [34]:
np.random.seed(seed=24)


In [35]:
random_integers = np.random.randint(low=1,high=5,size=100)
random_integers

array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4, 1, 4, 4, 3, 4, 4, 4, 4, 4, 4, 2, 3,
       4, 4, 2, 4, 2, 4, 1, 1, 3, 1, 4, 2, 2, 1, 4, 3, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 3, 3, 2, 1, 2, 4, 2, 1, 4, 3,
       1, 2, 1, 3, 4, 2, 3, 4, 1, 3, 2, 1, 1, 3, 3, 4, 3, 2, 4, 1, 4, 4,
       4, 4, 1, 4, 3, 2, 4, 4, 3, 3, 2, 4])

In [36]:
is_equal_to_3 = random_integers == 3


In [37]:
is_equal_to_3[:5]


array([ True, False, False, False, False])

In [38]:
sum(is_equal_to_3)


22

In [39]:
random_integers[is_equal_to_3]


array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [41]:
id_counts = df['ID'].value_counts()
dupe_mask = id_counts == 2
dupe_mask[0:5]

1bf3b4eb-d759    True
1b22b0ab-aba3    True
e39d23fe-aa5f    True
bbffebbc-e3c4    True
129c43ca-42ee    True
Name: ID, dtype: bool

In [11]:
dupe_ids = id_counts.index[dupe_mask]
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [42]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10) 


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
1959   1bf3b4eb-d759      70000    2          3         1   57     0      0   
2059   1bf3b4eb-d759          0    0          0         0    0     0      0   
5374   1b22b0ab-aba3      30000    2          1         2   30     0      0   
5474   1b22b0ab-aba3          0    0          0         0    0     0      0   
24221  e39d23fe-aa5f     130000    1          2         1   31     0      0   
24321  e39d23fe-aa5f          0    0          0         0    0     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
1959       0      0  ...      49103      45830      46769      2620      2730   
2059       0      0  ...          0          0          0         0         0   
5374       0      0  ...      32389      33142      33999      1600      2000   
5474       0      0  ...          0          0          0         0         0   
24221      0      0  ...     118293     121312     121162      5000      5000   
24321      0      0  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1959       1936      1700      1700      2000                           0  
2059          0         0         0         0                           0  
5374       1500      1200      1330      2500                           0  
5474          0         0         0         0                           0  
24221      5000      5000      5000      5000                           0  
24321         0         0         0         0                           0  

[6 rows x 25 columns]

In [43]:
df_zero_mask = df == 0


In [44]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)
sum(feature_zero_mask)


315

In [45]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()


In [46]:
df_clean_1['ID'].nunique()


29685

In [47]:
valid_pay_1_mask = df_clean_1['PAY_1'] != 'Not available'
valid_pay_1_mask[0:5]

0    True
1    True
2    True
3    True
4    True
Name: PAY_1, dtype: bool

In [48]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask,:].copy()


In [49]:
df_clean_2['PAY_1'] = df_clean_2['PAY_1'].astype('int64')
df_clean_2[['PAY_1', 'PAY_2']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26664 entries, 0 to 29999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PAY_1   26664 non-null  int64
 1   PAY_2   26664 non-null  int64
dtypes: int64(2)
memory usage: 624.9 KB


In [50]:
df_clean_2['EDUCATION'].replace(to_replace=[0, 5, 6], value=4, inplace=True)
df_clean_2['EDUCATION'].value_counts()

2    12458
1     9412
3     4380
4      414
Name: EDUCATION, dtype: int64

In [51]:
df_clean_2['MARRIAGE'].replace(to_replace=0, value=3, inplace=True)
df_clean_2['MARRIAGE'].value_counts()

2    14158
1    12172
3      334
Name: MARRIAGE, dtype: int64

In [52]:
df_clean_2['EDUCATION_CAT'] = 'none'


In [53]:
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)


EDUCATION EDUCATION_CAT
0          2          none
1          2          none
2          2          none
3          2          none
4          2          none
5          1          none
6          1          none
7          2          none
8          3          none
9          3          none

In [54]:
cat_mapping = {
    1: "graduate school",
    2: "university",
    3: "high school",
    4: "others"
}

In [55]:
df_clean_2['EDUCATION_CAT'] = df_clean_2['EDUCATION'].map(cat_mapping)
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

EDUCATION    EDUCATION_CAT
0          2       university
1          2       university
2          2       university
3          2       university
4          2       university
5          1  graduate school
6          1  graduate school
7          2       university
8          3      high school
9          3      high school

In [56]:
edu_ohe = pd.get_dummies(df_clean_2['EDUCATION_CAT'])
edu_ohe.head(10)



graduate school  high school  others  university
0                0            0       0           1
1                0            0       0           1
2                0            0       0           1
3                0            0       0           1
4                0            0       0           1
5                1            0       0           0
6                1            0       0           0
7                0            0       0           1
8                0            1       0           0
9                0            1       0           0

In [57]:
df_with_ohe = pd.concat([df_clean_2, edu_ohe], axis=1)
df_with_ohe[['EDUCATION_CAT', 'graduate school',
             'high school', 'university', 'others']].head(10)


EDUCATION_CAT  graduate school  high school  university  others
0       university                0            0           1       0
1       university                0            0           1       0
2       university                0            0           1       0
3       university                0            0           1       0
4       university                0            0           1       0
5  graduate school                1            0           0       0
6  graduate school                1            0           0       0
7       university                0            0           1       0
8      high school                0            1           0       0
9      high school                0            1           0       0

In [ ]:
df_with_ohe.to_csv('cleaned_data.csv', index=False)